<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>Electrolite</RootNamespace>
    <AssemblyName>Electrolite</AssemblyName>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Single-file publish -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- Assembly metadata -->
    <AssemblyTitle>Electrolite</AssemblyTitle>
    <Product>Electrolite</Product>
    <Description>ASUS Battery Charge Limit Manager</Description>
    <Company>alikarbasi.com</Company>
    <Copyright>Copyright (c) 2025 alikarbasi.com</Copyright>
    <Version>0.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>
